### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rennis250** [rbrich/sdf-text#1]
I recently found this and tested it out. Works for me and I would like to integrate it with a project that I hope to publicly release in the near future. Is it possible to at least put a license on this? Do you intend to make it available on crates.io?

Thanks!

**Comment by rbrich** [comment]
Yes, I'll add a licence. Probably MIT. Feel free to fork.

I intend to submit this to crates.io, but I don't think it's ready in the current state. There is neither any real API nor documentation. Though I still hope to return to this and finish it.

**Comment by rbrich** [comment]
Done: Apache License 2.0
